# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: 노균호 (Gyun-Ho Roh)
title: Data Scientist
email: iamguno@naver.com
phone: 010-3279-6977
website: www.github.com/iamguno

# Social links
github_username: iamguno
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: Gyunho Roh
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  [Birth] 1994.10.24
  [Interested In] Medical DL
  [Address] Daejeon, Republic of Korea

  사용 기술 : <mark>Java</mark> <mark>Spring</mark> <mark>JavaScript</mark> <mark>Node</mark>

  
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# test Section
# test_title: test

# Footer
footer_show_references: true

# Build settings
livereload: true

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
